# Generated by Django 5.2.5 on 2025-10-28 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinasi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_destinasi', models.CharField(max_length=150)),
                ('lokasi', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('kategori', models.CharField(blank=True, max_length=100, null=True)),
                ('gambar', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('role', models.CharField(default='user', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RencanaLiburan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('jumlah_orang', models.IntegerField(default=1)),
                ('estimasi_biaya', models.DecimalField(decimal_places=2, max_digits=12)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('destinasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.destinasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.user')),
            ],
        ),
        migrations.CreateModel(
            name='AktivitasRencana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_aktivitas', models.CharField(max_length=150)),
                ('waktu', models.TimeField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('rencana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas', to='data.rencanaliburan')),
            ],
        ),
    ]
